CREATE TABLE IF NOT EXISTS BASE2_TABLE_1(
       ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       T1_COLONNE_1 TEXT NOT NULL,
       T1_COLONNE_2 TEXT NOT NULL,
       T1_COLONNE_3 TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS BASE2_TABLE_2(
       ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       T2_COLONNE_1 TEXT NOT NULL,
       T2_COLONNE_2 TEXT NOT NULL,
       T2_COLONNE_3 TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BASE2_TABLE_3(
       ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       T3_COLONNE_1 TEXT NOT NULL,
       T3_COLONNE_2 TEXT NOT NULL,
       T3_COLONNE_3 TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BASE2_TABLE_4(
       ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       T4_COLONNE_1 TEXT NOT NULL,
       T4_COLONNE_2 TEXT NOT NULL,
       T4_COLONNE_3 TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BASE2_TABLE_5(
       ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       T5_COLONNE_1 TEXT NOT NULL,
       T5_COLONNE_2 TEXT NOT NULL,
       T5_COLONNE_3 TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BASE2_TABLE_6(
       ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       T6_COLONNE_1 TEXT NOT NULL,
       T6_COLONNE_2 TEXT NOT NULL,
       T6_COLONNE_3 TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BASE2_TABLE_7(
       ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
       T7_COLONNE_1 TEXT NOT NULL,
       T7_COLONNE_2 TEXT NOT NULL,
       T7_COLONNE_3 TEXT NOT NULL
);
